### ISSUE TITLE
Charm interferes with the mod

### ISSUE THREAD

**Issue by Atlas1124** [mschae23/grind-enchantments#10]
Hey man, did some testing (going through and adding every single mod one by one until your mod stopped working). Just wanted to let you know that the problem is **_Charm_**. I made a modpack with just your mod and **_Charm_**, and it doesn't let you put a book in the bottom slot. Delete **_Charm_**, and your mod works.

**Comment by mschae23** [comment]
I think Charm has a very similar feature, so it makes sense that it conflicts. I don't know if I can fix that on my side, though.

**Comment by TheOrionsun** [comment]
Is it possible to have Charm remove your code as he gives credit to your mod for it? I have tried to disable it in charm, but it did not help....

**Comment by mschae23** [comment]
> Is it possible to have Charm remove your code as he gives credit to your mod for it? I have tried to disable it in charm, but it did not help....

I don't think I can do much about it. Charm disables its module automatically if this mod is installed, but the mixins probably can't be disabled.
