### ISSUE TITLE
Compatibility with limitless

### ISSUE THREAD

**Issue by RaXorX** [mschae23/grind-enchantments#11]
https://github.com/mschae23/grind-enchantments/issues/4
Similar thing but with limitless, could you instead make a config file that maybe makes use of the different mods out there that might be doing the same thing and you could just spcify which mod it is and it'll simply work with it normally?

I just wasted all the xp haha cause I didn't look at it.

**Comment by mschae23** [comment]
> could you instead make a config file that maybe makes use of the different mods out there that might be doing the same thing and you could just spcify which mod it is and it'll simply work with it normally?

That's sadly not how mod compatibility works, sorry.

I'll look into this.

**Comment by mschae23** [comment]
Okay, I just looked, and the version published on Maven seems to be a bit outdated.
Also, the repository uses some custom plugin that doesn't work for me, so I can't build the newest version myself either.

**Comment by RaXorX** [comment]
> > could you instead make a config file that maybe makes use of the different mods out there that might be doing the same thing and you could just spcify which mod it is and it'll simply work with it normally?
> 
> That's sadly not how mod compatibility works, sorry.
> 
> I'll look into this.

No no, well I sort of meant this, look at some of the more common/popular mods which do the exact same thing. And make it compatible with them all, like there's that fair enchantment (for 1.16.5 and below), limitless (1.17 and below), tax free enchantments (1.17 and below), etc etc. Just some of the more popular ones. Then include a config file so in case anyone uses one of the mods, they could activate that feature for this too. Was just a thought in my head. 
Anyways, are we talking about the same mod? https://github.com/auoeke/limitless

**Comment by mschae23** [comment]
> No no, well I sort of meant this, look at some of the more common/popular mods which do the exact same thing. And make it compatible with them all, [...]. Just some of the more popular ones. Then include a config file so in case anyone uses one of the mods, they could activate that feature for this too. Was just a thought in my head.

If I added compatibility with those mods, a config file wouldn't be needed anymore.

> Anyways, are we talking about the same mod? https://github.com/auoeke/limitless

Yes. The author uses their own Gradle plugin that doesn't work for me locally, and the files published on Maven are a few versions behind.

**Comment by RaXorX** [comment]
Ah fair enough. Well you can contact the dev, he pretty much responds within a day and is quite active too. Hope to see this resolved if it can, no pressures though if there are any disagreements.

**Comment by auoeke** [comment]
I have published the latest version of limitless to my Maven repository (https://maven.auoeke.net) but I think that making a library dedicated to this instead of another mod relying on limitless for it is a better idea.
limitless' normalization logic is in `ExperienceUtil#addExperienceLevelsRelatively`.

**Comment by mschae23** [comment]
> I think that making a library dedicated to this instead of another mod relying on limitless for it is a better idea.

There is Fair Enchanting, which this mod already supports.

**Comment by auoeke** [comment]
limitless is now compatible with Tax Free Levels. I don't think that we need to do anything else.

**Comment by mschae23** [comment]
> limitless is now compatible with Tax Free Levels. I don't think that we need to do anything else.

Great! I don't think there's anything else that needs to be done then either.

**Comment by RaXorX** [comment]
So, limitless + tax free levels + grind enchantments. Is that the combo that'd make it work properly? @auoeke @mschae23

**Comment by auoeke** [comment]
Should be.
