### ISSUE TITLE
Request in a form of plugin

### ISSUE THREAD

**Issue by PecaPereca** [mschae23/grind-enchantments#12]
Hello. I would love to see this fabric mod in form of a plugin for paper/bukkit/spigot, if possible, it would really help me and players on my server. If it is possible, please do it if you can, if it isnt, well, then i will find something similiar maybe, but i wasnt able to, so i requested it here.

**Comment by mschae23** [comment]
Hello! It should be possible to create a plugin out of this, but I don't think I will do that myself. As far as I know, Paper / Spigot don't support Mixins, which this mod uses. That means that it will have to be done with their API, which I don't want to learn now.

However, disenchanting items is a very common concept, so I would be surprised if there are no plugins for that already.
