### ISSUE TITLE
Suggestion: consume item when transferring to book

### ISSUE THREAD

**Issue by MeeniMc** [mschae23/grind-enchantments#13]
To improve balance, it may be good to actually consume the origin item when grinding enchants to books. Player would then have to choose between: 
1. grinding without a book, get back the item and gain some xp
2. grinding with a book, get back the enchant and cost some xp

This could be a configurable toggle with prior behavior as default.

**Comment by mschae23** [comment]
Sure, I can add this to the config.

**Comment by mschae23** [comment]
Thank you for the suggestion! I have added this to the config for disenchanting now.
