### ISSUE TITLE
Allow removing curses

### ISSUE THREAD

**Issue by chimericdream** [mschae23/grind-enchantments#16]
It would be nice to have a config that let you remove curses onto books as well as enchantments. The default could be `false` to preserve the current behavior.

**Comment by mschae23** [comment]
I'm personally against being able to remove curses, but sure, I can add that to the config.

**Comment by chimericdream** [comment]
I completely understand. I go back and forth on it myself. Thanks for making it an option!

**Comment by mschae23** [comment]
Sorry, I forgot about this. I have now released a new version (1.5.0) with this feature.

**Comment by Xastabus** [comment]
Hi, I updated my server to 1.5.0 but it didn't add the option for this feature to the config file.  I tried adding it myself but I'm not sure I got it right because it's not working.

https://bin.bloom.host/evufudipoq

**Comment by mschae23** [comment]
> Hi, I updated my server to 1.5.0 but it didn't add the option for this feature to the config file. I tried adding it myself but I'm not sure I got it right because it's not working.
> 
> https://bin.bloom.host/evufudipoq

The config field is `allow_removing_curses`. You can also always delete (or rename) the config file to let the mod regenerate it, which shows all config options.
