### ISSUE TITLE
Add a way to reset repair cost

### ISSUE THREAD

**Issue by dull4h4n** [mschae23/grind-enchantments#20]
I mentioned this to you in a comment on curse a while back. I just wondered if you had given it any further thought.

The suggestion is to be able to take a book that combined multiple enchants, like when combining 4 Protection II books to make a single Protection IV. It has an NBT 2 tag which makes it very expensive. The idea is to be able to put that NBT2 version of Prot IV and then grind the enchant and create a fresh NBT1 Prot IV that isn't as expensive to use.

**Comment by mschae23** [comment]
Sure, I could implement that. How should this be done? Just putting in the enchanted book doesn't work for this, as that is already used for removing the enchantments in vanilla. Maybe by adding an additional empty book?
Also, should this work for tools and armor as well?

Anyway, I think this would probably be disabled by default though, as it isn't a very intuitive feature.

**Comment by dull4h4n** [comment]
Its just putting a book into grinder under an enchanted book. This is how it worked with the old 1.12 disenchanting mod from years ago. I think most people who used disenchanters would be familiar with the ability to remove the NBT and huge cost with manually enchanted books.

**Comment by dull4h4n** [comment]
Not sure why it would need to be disabled by default, it wouldn't affect anyone who was not familiar with putting a book in grinder under another book (rather than an item). There would be no other reason to do that.

**Comment by mschae23** [comment]
I've added this new functionality to the mod now (although yes, sorry, disabled by default).

> Its just putting a book into grinder under an enchanted book.

This wouldn't work here, because that combination of items is already used by the "moving enchantments between books" feature. Instead, I've now made it so you have to put a diamond into the bottom slot instead, but that is configurable.
