### ISSUE TITLE
Suggestion: Other ways to see the cost

### ISSUE THREAD

**Issue by Harvle** [mschae23/grind-enchantments#23]
If people don't use this mod on the client side (i have a server which uses server-side mods only), currently it's impossible to see the cost. I have thought up a few ways this could be achieved:
- Send a message in chat whenever the item is updated
- Change the name of the grindstone GUI (if this is possible with fabric)
- Add a lore line to the "result" item that'll be removed on completion (if this is possible with fabric)
- Send an actionbar

Obviously, the current way is the best, so if the player has the mod, it'd use that and ignore these, otherwise there would be a config line to say which one to use, i.e `no_mod_cost_display: "chatmessage|guiname|resultlore|actionbar"` (can't think of a good key name).

Ideally, this text lines would be configurable as well.

Thanks for taking time to read this! :)

**Comment by Harvle** [comment]
(Not sure if this is of any use) Carpet detects if the mod exists on the client, however it appears to use some kind of "handshake" that the client mod sends to the server on join, seems out-of-scope for this mod to add something like that.

If you can't find a way to do it, could you do something more simple by just checking the client's version to see if the user logged in with a Fabric client, then just assume they have the mod? Obviously it's not a great solution, but just an idea! I think some anti-cheat mods/plugins use this to detect if a player is using vanilla, fabric, forge, optifine, etc, i'm not sure if this method also supports looking at the individual installed fabric mods though.

I agree item lore would suit the mod best, hopefully you're able to figure something out with it. :)

**Comment by mschae23** [comment]
> (Not sure if this is of any use) Carpet detects if the mod exists on the client, however it appears to use some kind of "handshake" that the client mod sends to the server on join, seems out-of-scope for this mod to add something like that.

From what I've seen, it should be possible to do this by letting the client send a packet to the server which effectively disables the alternative cost display for that player. This would mean adding a dependency on Fabric API (which is currently not required), but I may try doing this in the future. For now, a simple config option should be fine, but would apply to all players on the server.

> could you do something more simple by just checking the client's version to see if the user logged in with a Fabric client, then just assume they have the mod?

I'm not sure if Fabric actually sends the client brand when joining a server.

> I agree item lore would suit the mod best, hopefully you're able to figure something out with it. :)

I'll try!

**Comment by mschae23** [comment]
So, I actually got this working with item stack lore, and it is also colored green or red depending on whether the player has enough XP (just like the text that is displayed if you have the mod installed).

From my testing, the issue that you can still take the item if you don't have enough XP (which will be a ghost item that disappears when the inventory is synced) didn't seem to appear, but I can't guarantee that.

This behavior is disabled by default, and can be enabled by adding an option in the config for now (which also means that players who have the mod will see the enchantment cost twice, but this shouldn't be a major problem).

**Comment by Harvle** [comment]
Hi, sorry for the late response, been busy, but well done for figuring this out! That sounds great, thanks for taking the time to implement this, looking forward to using it! :)

**Comment by Harvle** [comment]
Just started using it, works great. In console there's a "Adding level cost lore" message every time an item has the lore applied, is this intentional (seems like a debug message)?

**Comment by mschae23** [comment]
> Just started using it, works great. In console there's a "Adding level cost lore" message every time an item has the lore applied, is this intentional (seems like a debug message)?

Yes, it's a debug message, looks like I forgot about it. I'll remove it in the next release.
