### ISSUE TITLE
Game crashed using 1.6.4 version

### ISSUE THREAD

**Issue by linzexin022** [mschae23/grind-enchantments#26]
Hi, I tried launching the game with 1.6.4 version of Grind Enchantments but failed.
Game version: 1.18.2
Fabric Loader: 0.14.7
Fabric API: 0.55.1
Grind Enchantments version: 1.6.4
Here's the crash report:
[crash-2022-06-10_18.58.41-client.txt](https://github.com/mschae23/grind-enchantments/files/8878271/crash-2022-06-10_18.58.41-client.txt)

**Comment by mschae23** [comment]
Looks like there was a change in 1.19, which means that the 1.19 file won't work with 1.18.x anymore. I'll release a separate file for these versions.
