### ISSUE TITLE
not able to put book in grindstone

### ISSUE THREAD

**Issue by Cole9290** [mschae23/grind-enchantments#27]
i dont know if i missed something but following the curseforge page i did everything right...

**Comment by mschae23** [comment]
Is the mod installed on the server?

**Comment by Cole9290** [comment]
I dunno, it’s a solo world without any others. I guess that is on server right or is there another mods folder I don’t know about?

**Comment by mschae23** [comment]
Okay, if it is in a singleplayer world, the distinction between client and server doesn't matter. Unfortunately, I can't reproduce this myself, so I don't really know what the problem could be.

**Comment by mschae23** [comment]
I'm closing this issue now, because I cannot reproduce it.
Feel free to open another one with more information if this is still happening.
