### ISSUE TITLE
Cost is not showing in Grindstone?

### ISSUE THREAD

**Issue by astridos2go** [mschae23/grind-enchantments#28]
Hi, I'm using this mod on a server of mine, and I really enjoy it. The only issue I've encountered is that the grindstone does not show the player how much the disenchantment costs. In the image on the Modrinth page, the cost is shown, so I wasn't sure if that was supposed to happen or not.

**Comment by mschae23** [comment]
Yes, the cost is supposed to be shown by default. The mod has to be installed on both the server and the client for that.

You can also enable the alternative cost display in the config (on the server side), which will show the cost as lore on the result item (clients do not need the mod in that case).

**Comment by astridos2go** [comment]
Oh fantastic, thank you for the clarification. I am using it on a Vanilla style server, so the alternative method is perfect!
