### ISSUE TITLE
Server hangs up on restart

### ISSUE THREAD

**Issue by DanShu15** [mschae23/grind-enchantments#3]
Unless this is somehow an old crash report, I'm not sure why it would hang up in this situation.
It's worked flawlessly since last update, but when I install DiscordConnect and try to do a server shut down or restart it saves world data and then hangs up. Without DiscordConnect it works as expected and as before.
I submitted the bug report to DiscordConnect and was sent your way over the hang up and crash. Logs are all posted here https://github.com/AMereBagatelle/DiscordConnect/issues/1

**Comment by mschae23** [comment]
You have version 1.1.0+1.15.2 installed on the server. Can you update to the newest version and look if this still occurs? The error message seems to be the same as from the last crash.

**Comment by DanShu15** [comment]
it's definitely 1.1.2+ 1.15.2
Must be an old log, I'll clear them entirely and update in a sec

**Comment by DanShu15** [comment]
Woops I'm stupid, that was from the 5th LOL
