### ISSUE TITLE
Regular use of grindstone is not working correctly

### ISSUE THREAD

**Issue by astridos2go** [mschae23/grind-enchantments#31]
Hi, I have this mod on a server of mine, and I really enjoy using it, but I've noticed that when I try to use my grindstone normally – i.e., disenchant an item, and get experience back – it doesn't work like it's supposed to. 

Instead, when I put an item in a grindstone with no book underneath, it does in fact disenchant the item, BUT, it also places an 'Enchanted Book' (sometimes empty, sometimes with enchantments) in top disenchantment slot. Not only that, but it CHARGES me experience for this enchanted book. Experience that is not returned even by disenchanting the book. 

Giving the enchanted books are often empty, I'm assuming this is a bug and not the intended operation of the mod. 

Please let me know if there's any more information you need from me, as I would love to see this issue resolved if possible!

Thank you so much!

**Comment by astridos2go** [comment]
It may be important to note that I am currently running v2.0.0-beta

**Comment by mschae23** [comment]
Sorry for only responding this late. I have now released v2.0.0-beta.2, which should fix this issue.
