### ISSUE TITLE
is this required only server side or both client and server?

### ISSUE THREAD

**Issue by kinglarry4444** [mschae23/grind-enchantments#37]
wanting to add this to my server but cant find info if this is a server side mod

please respond with server side or with both client and server

**Comment by mschae23** [comment]
The mod is only required on the server side. It can optionally be installed on the client as well, which allows seeing the enchantment cost (alternatively, you can enable the `alternative_cost_display_enabled` option in the config).

**Comment by kinglarry4444** [comment]
> 

thanks
