### ISSUE TITLE
3.0b1 produces 'random enchantment book'

### ISSUE THREAD

**Issue by MeeniMc** [mschae23/grind-enchantments#39]
### Versions

1.19.3/3.0b1

### Problem description 

When a non-enchanted item is put in the grinder with a stack of books, the following 2 defects are observed

1. The produce slot proposes to create a "random enchantment book", and such book can be obtained. 
2. A full stack of books is consumed when producing the "random enchantment book" if such a stack was put in the grinder.

### Expected

1. When a non-enchanted item is in the grinder, adding a book should have no produce
2. a single book should always be consumed

### v2.0

This bug is not present in v2 of the mod.

**Comment by mschae23** [comment]
I can only investigate this later today, but it's interesting that this only happens in 3.0, as I believe I only changed the way configs work there.

What is a "random enchantment book"? Is it one with no enchantments on it, or an actual random one?

**Comment by mschae23** [comment]
I can't reproduce this with version 3.0.0-beta.1 on 1.19.3. When putting an unenchanted item and any number of books into the grindstone, nothing happens for me.

Could this be a mod compatibility issue? Do you have any other mods installed that modify the grindstone?

**Comment by MeeniMc** [comment]
It IS a mod compatibility issue!

EMI Loot causes this. It's probably on their side too, since I had a similar issue with Lootr in the past, should have remembered.

**Comment by MeeniMc** [comment]
Issue is with other mod

**Comment by mschae23** [comment]
Alright. Sorry for not looking into this yet. I was meaning to do that, but didn't have time so far.
