### ISSUE TITLE
Compatibility with Fair Enchanting

### ISSUE THREAD

**Issue by copygirl** [mschae23/grind-enchantments#4]
Would it be possible for the disenchantment cost of the grindstone to be affected by [Fair Enchanting](https://www.curseforge.com/minecraft/mc-mods/fairenchanting)'s cost logic if it is installed?

The mod makes enchanting and anvil recipes cost the same amount of flat experience points, rather than consuming more the higher level you are. It does make some low-level enchantment operations cheaper, but I no longer have to worry about wasting my experience because I like to accumulate levels.

Thank you for the wonderful mod!

**Comment by mschae23** [comment]
Done in deab1aab17b9be39b86957a3d238852f9b083d73. Sorry for the delay.

**Comment by copygirl** [comment]
Sweet. Thank you so much!
