### ISSUE TITLE
Config cost factor wrong display

### ISSUE THREAD

**Issue by FuturPlanet** [mschae23/grind-enchantments#41]
Changing the costfactor does work but its still displayed wrong on the gridstone

**Comment by mschae23** [comment]
I know this is a bit late, but do you have any information that could help reproduce the issue, like the Minecraft and mod version?
Also, I've just released the mod for 1.19.4, and it's possible that it is fixed there. It may also be that the config isn't read correctly – try checking if the log contains `Error decoding config` messages.
