### ISSUE TITLE
[Bug] Changing config doesn't work

### ISSUE THREAD

**Issue by Zano1999** [mschae23/grind-enchantments#48]
This is the configuration where I tried to set the disenchantment cost based on the sum of the spell power (Efficiency III = 3 levels), it doesn't seem to work.

{
  "allow_removing_curses": false,
  "dedicated_server_options": {
    "alternative_cost_display_enabled": false
  },
  "client_options": {
    "show_enchantment_cost": true
  },
  "disenchant_to_book": {
    "enabled": true,
    "consume_enchanted_item": false,
    "cost_function": {
      "function": {
        "type": "grindenchantments:count_levels"
      },
      "factor": 1.0,
      "offset": 0.0,
      "type": "grindenchantments:transform"
    }
  },
  "move_enchantments": {
    "enabled": true,
    "cost_function": {
      "function": {
        "function": {
          "normal_factor": 1.0,
          "treasure_factor": 2.0,
          "type": "grindenchantments:count_levels"
        },
        "type": "grindenchantments:first_enchantment"
      },
      "factor": 0.5,
      "offset": 0.5,
      "type": "grindenchantments:transform"
    }
  },
  "version": 2
}

**Comment by mschae23** [comment]
I believe there are two fields missing here:
```jsonc
"function": {
    "type": "grindenchantments:count_levels",
    "normal_factor": 1.0,
    "treasure_factor": 1.0 // You can use this as a cost multiplier for "treasure" enchantments like Mending
}
```

**Comment by Zano1999** [comment]
Ok, but this doesn't solve the problem, I don't have problems with "treasure" enchantments but with any

**Comment by mschae23** [comment]
These fields have to be there for the config to load correctly, though, even if you don't use them. 
I can't see any other problems, so if you have added them and it still doesn't work, try looking in the game's logs (`.minecraft/logs/latest.log`) for any errors mentioning the config.

**Comment by Zano1999** [comment]
The config file i used is a new generated one with only the desired words changed, but the order of the strings and the position of the punctuation is unchanged.
Here the latest log: https://pastebin.com/MzAZ2891

**Comment by Zano1999** [comment]
{
  "allow_removing_curses": false,
  "dedicated_server_options": {
    "alternative_cost_display_enabled": true
  },
  "client_options": {
    "show_enchantment_cost": true
  },
  "disenchant_to_book": {
    "enabled": true,
    "consume_enchanted_item": false,
    "cost_function": {
        "function": {
          "normal_factor": 1.0,
          "treasure_factor": 1.0,
          "type": "grindenchantments:count_levels"
        },
      "factor": 1.0,
      "offset": 0.0,
      "type": "grindenchantments:transform"
    }
  },
  "move_enchantments": {
    "enabled": true,
    "cost_function": {
      "function": {
        "function": {
          "normal_factor": 1.0,
          "treasure_factor": 1.0,
          "type": "grindenchantments:count_levels"
        },
        "type": "grindenchantments:first_enchantment"
      },
      "factor": 1.0,
      "offset": 0.0,
      "type": "grindenchantments:transform"
    }
  },
  "version": 2
}
