### ISSUE TITLE
This does not seem to work

### ISSUE THREAD

**Issue by MCGamerDad** [mschae23/grind-enchantments#5]
Hello, I installed this mod without issues. When placing the enchanted item and the book on the grindstone, it showed an enchanted book in the output. However, I simply received the un-enchanted item without and enchanted book.

I am playing multiplayer, 1.16.4 Fabric. I have not tried singleplayer yet.

Thank you

**Comment by mschae23** [comment]
Is the mod installed on the server side too?

**Comment by MCGamerDad** [comment]
No. I thought that since it did not create a "new" item that it would not
need to be.

**Comment by mschae23** [comment]
Client-side mods can only do visual changes (which is why it showed the enchanted book first), anything that changes gameplay is required on the server.

**Comment by MCGamerDad** [comment]
ok thanks. I'll look into it getting added
