### ISSUE TITLE
Enchanted book is there but I can't take it

### ISSUE THREAD

**Issue by Galabeam** [mschae23/grind-enchantments#51]
![image](https://github.com/mschae23/grind-enchantments/assets/68124962/b43109e8-2fdd-4aee-b981-b309682fed56)
Whenever I click the book, it instantly puts it back.
I'm using 1.20.2 on a fabric server.
The mod is installed on the server and not my client, the reason for this is I want mods that my friends don't have to download.

**Comment by mschae23** [comment]
> Whenever I click the book, it instantly puts it back.

Are you sure that you have enough XP to disenchant the book? If the mod is not installed on the client, you'll have to set `alternative_cost_display_enabled` to `true` in the options, which will show the enchantment cost in the tooltip.

**Comment by Galabeam** [comment]
Oh, I completely forgot about that config bool, thank you so much.
