### ISSUE TITLE
Client Side Required 1.20.5

### ISSUE THREAD

**Issue by ike2117** [mschae23/grind-enchantments#52]
Just updated my server and installed the latest version of the mod for 1.20.5, however I am unable to connect as its being stated there is a mod mismatch. In 1.20.4, only the server required the mod

**Comment by mschae23** [comment]
Hm, in my testing this case worked fine. Although I have a suspicion on what could cause this. Do you have Fabric API installed on the client? Could you try connecting without it? If that works, then I'll unfortunately have to change the implementation a bit to support this.

**Comment by ike2117** [comment]
I just tired without fabric loaded and it seems to be working. For context aswell, I'm using Lunar with Fabric for 1.20.5

**Comment by mschae23** [comment]
I just released version 3.2.1, which should fix the issue.

Unfortunately, I had to remove the "alternate server-side cost display" feature for the time being. I'd love to bring it back, but I've yet to find a good way to implement it (the way it worked previously was really hacky too).
