### ISSUE TITLE
Same Issue as #51 where enchanted book shows up, but can't take, solution in #51 doesn't work

### ISSUE THREAD

**Issue by JiggityJohn** [mschae23/grind-enchantments#54]
Running MC 1.21 for a fabric server
the config currently has 

"alternative_cost_display_enabled": true

as recommended for a server only implementation mod, but the enchanted book still does not go into invo

**Comment by mschae23** [comment]
You need to have enough XP levels to take the book. Unfortunately, I had to remove the alternative cost display for the time being, so the config option currently does nothing. As a workaround, you can install the mod on the client and make sure the configs match, which should let you see the required XP cost. Sorry!
