### ISSUE TITLE
[Bug] 1.20.6 Enchantments taken from items crashing game when trying to use them in anvil

### ISSUE THREAD

**Issue by rottenhewie** [mschae23/grind-enchantments#57]
Taking enchantments from armor and trying to put them on another piece of armor crashes the game, also on relog the armor I was trying to combine no longer exist. Unsure if its the same with other items but i'm assuming it has something to do with the enchantments themselves.
Sorry if this is the wrong log or your mod isn't at fault.
[crash-2024-07-12_04.31.59-client.txt](https://github.com/user-attachments/files/16188251/crash-2024-07-12_04.31.59-client.txt)

**Comment by mschae23** [comment]
This looks like it is caused by "Netherite extras", or maybe it's a compatibility issue between these two mods. Can you check whether it works with this mod (or Netherite extras) alone?

**Comment by rottenhewie** [comment]
I tested without Netherite extras and it didn't crash so that's probably the issue. I updated to a new version of the mod and the issue seems to be fixed, sorry for the bother!

**Comment by mschae23** [comment]
Alright, that's great!
