### ISSUE TITLE
crash when rendering screen?

### ISSUE THREAD

**Issue by ChunkyRagu89** [mschae23/grind-enchantments#6]
for some reason grind enchantments is starting to crash the game when i try to put a book and an enchanted book/item in the grindstone (what youre supposed to do if you want to disenchant an item), and says its a rendering screen error in the crash log, not sure whats causing this but it was working before i updated to the mods latest version (the 1.16.3 version of the mod)
crash log: https://hastebin.com/usiwaxowad.yaml

**Comment by mschae23** [comment]
The `1.1.3+20w51a` version of the mod only works in 1.17 snapshots. You'll have to use the older version (`1.1.3+1.16.3`).

**Comment by ChunkyRagu89** [comment]
ohhhh i gotcha, sorry about that i thought it was for 1.16.4 too (1.17 +1 is what i saw, didnt check it out though)
ill be more aware next time, thanks for replying!

**Comment by mschae23** [comment]
I accidentally marked it as 1.16.3 and 1.16.4 too on CurseForge, so it isn't your fault. Thanks for reporting this!
