### ISSUE TITLE
Turn off "ignore curses"

### ISSUE THREAD

**Issue by DreezyMoto** [mschae23/grind-enchantments#62]
looking for a way to disable the ignore curses settings so that i can "uncurse" items. can anyone help me out?

**Comment by mschae23** [comment]
In the config file (`.minecraft/config/grindenchantments.json`), find `"cursed_enchantments": "ignore"`, and change `ignore` to `allow`. That should be enough to be able to disenchant curses.

**Comment by DreezyMoto** [comment]
That worked, thank you!
