### ISSUE TITLE
Disable Cost

### ISSUE THREAD

**Issue by jaboiiiiii** [mschae23/grind-enchantments#63]
Benn trying for like an hour to disable the cost or at least make it super super cheap - my world has a mod that lets me over power enchantments and taking a level 40 inchant off cost like 70 levels... it makes this mod unusably expensive.

**Comment by jaboiiiiii** [comment]
any help to make it free would be super apreciated

**Comment by jaboiiiiii** [comment]
i turned the factor and offset to 0 and it says its gonna be free then it removes levels anyway. even if i keep the offset (makes it display 1 level cost for  moving an enchant to a book... but then it takes 15+ levels.. and  i missing a number to change or?

**Comment by mschae23** [comment]
> i turned the factor and offset to 0 and it says its gonna be free then it removes levels anyway. even if i keep the offset (makes it display 1 level cost for moving an enchant to a book... but then it takes 15+ levels.. and i missing a number to change or?

Are you playing in multiplayer? This sounds like the config on the server is different from the one on the client.

> my world has a mod that lets me over power enchantments and taking a level 40 inchant off cost like 70 levels... it makes this mod unusably expensive.

You may be interested in changing `count_min_power` and `count_levels` to `count_enchantments` (and tweaking the factors and offsets then, of course), which will make the enchantment level irrelevant in the cost.

**Comment by jaboiiiiii** [comment]
absolute fire!!! this fixxed it! i also had to delete the config and regenerate it before the change would take effect! im now transfering free! the _enchantments with 0 offests anf factors worked!

**Comment by mschae23** [comment]
That's great, glad I could help!
