### ISSUE TITLE
deny disenchant by item - enhancement

### ISSUE THREAD

**Issue by superon** [mschae23/grind-enchantments#7]
could you add an option to deny disenchanting particular items?
thinking about balance and compat with enchant giver

alternatively deny or accept particular enchants?   or both items and enchants

**Comment by mschae23** [comment]
Hello! Sorry for not responding sooner.
I'll look into adding compatibility with Enchant Giver.

**Comment by superon** [comment]
<3 lovely

**Comment by mschae23** [comment]
While it looks like EnchantGiver hasn't updated past 1.17, I've just implemented this feature anyway – you can now deny certain items from being used in this mod by adding them to the `items` list in the `filter` section of the configuration file.
