### ISSUE TITLE
Unable to Place Book in Grindstone

### ISSUE THREAD

**Issue by Atlas1124** [mschae23/grind-enchantments#9]
Hi, just downloaded this mod for 1.17 and it only allows me to put an enchanted item in the top slot of the grindstone. When I try to put a book on the bottom slot, it doesn't let me. I can "hover" over it with the book, but not actually place it so I can remove the enchantment from the item and put it on the book. 
![Screenshot 2021-06-26 053854](https://user-images.githubusercontent.com/86515884/123508984-d6819680-d640-11eb-813d-570aa69dfeb6.png)

**Comment by mschae23** [comment]
Does it work without other mods? In your screenshot, it definitely looks like there's another mod modifying the grindstone, so it could be a conflict with that.

**Comment by Atlas1124** [comment]
Just tested it, it works perfectly fine! Thank you for the fast response. Now I have to find what mod is interfering with it.

**Comment by SirWishbone** [comment]
Did you end up figuring out what mod causes issues with Grind Enchantments? I have your same issue but am working with 297 other mods and would love to not have to sort through all of them!!!!
